services:
  nginx:
    build:
      context: .
      dockerfile: stream-service/Dockerfile.nginx
    ports:
      - "10000:80"
    depends_on: [backend]
    restart: always

  backend:
    build:
      context: ./stream-service
      dockerfile: Dockerfile.backend
    expose: ["10000"]
    restart: always
