server {
    listen 80;
    server_name _;

    location /develop/ {
        proxy_pass http://vite-dev:5173/develop/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://backend:10000;
        proxy_set_header Host $host;
    }
    location /detect/ {
        proxy_pass http://backend:10000;
        proxy_set_header Host $host;
    }

    location = / {
        return 302 http://$http_host/develop/;
    }
}
